import './index.css'
export { AutoMergeTable } from './components/AutoMergeTable'
export { TableHeader } from './components/TableHeader'
export { TableBody } from './components/TableBody'
export type { Cell } from './types/Cell'